# Generated by Django 3.2.9 on 2022-01-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logger', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loggerdata',
            old_name='connection',
            new_name='system_message',
        ),
        migrations.AddField(
            model_name='loggerdata',
            name='task_id',
            field=models.CharField(default='NN', max_length=128),
            preserve_default=False,
        ),
    ]
