FROM python:3.8.3-alpine

LABEL author="Robert Tadeusz Kucharski"

ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /usr/src/app
COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . ./
