# Generated by Django 3.2.9 on 2022-01-16 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fsmtemplate',
            name='command',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='fsmtemplate',
            name='device_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.devicetype'),
        ),
        migrations.DeleteModel(
            name='DeviceTypeTemplate',
        ),
    ]
