# Generated by Django 3.2.9 on 2022-01-14 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20220114_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicetypetemplate',
            name='value',
        ),
        migrations.RemoveField(
            model_name='fsmtemplate',
            name='value',
        ),
    ]
