# Generated by Django 3.2.9 on 2022-01-16 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20220116_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsmtemplate',
            name='device_template',
            field=models.BooleanField(default=False),
        ),
    ]
