# Generated by Django 3.2.9 on 2022-01-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('automation', '0003_fsmtemplate_device_template'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='devices',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.Device'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='groups',
            field=models.ManyToManyField(blank=True, null=True, to='inventory.Group'),
        ),
    ]
