# Generated by Django 3.2.9 on 2022-01-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_auto_20220116_1935'),
    ]

    operations = [
        migrations.AddField(
            model_name='policy',
            name='templates',
            field=models.ManyToManyField(blank=True, null=True, to='automation.FsmTemplate'),
        ),
    ]
