# Generated by Django 3.2.9 on 2022-01-17 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('automation', '0005_policy_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='policymanager',
            name='policy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='automation.policy'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='policy',
            name='devices',
            field=models.ManyToManyField(blank=True, to='inventory.Device'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='groups',
            field=models.ManyToManyField(blank=True, to='inventory.Group'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='task',
            field=models.IntegerField(choices=[(0, 'Device configuration'), (11, 'Device check'), (12, 'Device collect')], default=0),
        ),
        migrations.AlterField(
            model_name='policy',
            name='templates',
            field=models.ManyToManyField(blank=True, to='automation.FsmTemplate'),
        ),
    ]
