# Generated by Django 3.2.9 on 2022-01-17 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_auto_20220117_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policymanager',
            name='description',
        ),
        migrations.RemoveField(
            model_name='policymanager',
            name='name',
        ),
    ]
