# Generated by Django 3.2.9 on 2022-01-17 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_auto_20220117_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='policymanager',
            name='running',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='policymanager',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
