# Generated by Django 3.2.9 on 2022-01-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0009_auto_20220117_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='fsmtemplate',
            name='required',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
