# Generated by Django 3.2.9 on 2022-01-14 15:39

from django.db import migrations, models
import main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credential',
            name='password',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='color',
            name='description',
            field=models.CharField(default='ModelBase description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, max_length=256, validators=[main.validators.DescriptionValueValidator()]),
        ),
        migrations.AlterField(
            model_name='credential',
            name='description',
            field=models.CharField(default='ModelBase description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, max_length=256, validators=[main.validators.DescriptionValueValidator()]),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(default='ModelBase description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, max_length=256, validators=[main.validators.DescriptionValueValidator()]),
        ),
        migrations.AlterField(
            model_name='devicetype',
            name='description',
            field=models.CharField(default='ModelBase description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, max_length=256, validators=[main.validators.DescriptionValueValidator()]),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(default='ModelBase description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 256 digits, letters and special characters -, _, . or spaces.'}, max_length=256, validators=[main.validators.DescriptionValueValidator()]),
        ),
    ]
