# Generated by Django 3.2.9 on 2021-12-23 13:12

from django.db import migrations, models
import inventory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='hexadecimal',
            field=models.CharField(error_messages={'blank': 'Colour field is mandatory.', 'invalid': 'Enter the correct colour value. It must be a 3/6 hexadecimal number with # character on begining.', 'null': 'Colour field is mandatory.', 'unique': 'Color with this hexadecimal value already exists.'}, max_length=7, unique=True, validators=[inventory.validators.ColorValueValidator()]),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 8 to 32 digits, letters and special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Color with this name already exists.'}, max_length=32, unique=True, validators=[inventory.validators.NameValueValidator()]),
        ),
        migrations.AlterField(
            model_name='credential',
            name='name',
            field=models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 8 to 32 digits, letters and special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Credentials with this name already exists.'}, max_length=32, unique=True, validators=[inventory.validators.NameValueValidator()]),
        ),
        migrations.AlterField(
            model_name='credential',
            name='username',
            field=models.CharField(error_messages={'blank': 'Username field is mandatory.', 'invalid': 'Enter the correct username value.', 'null': 'Username field is mandatory.'}, max_length=64),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(error_messages={'blank': 'IP / DNS name field is mandatory.', 'invalid': 'Enter a valid IP address or DNS resolvable hostname. It must contain 4 to 32 digits, letters and special characters -, _, . or spaces.', 'null': 'IP / DNS name field is mandatory.', 'unique': 'Device with this hostname already exists.'}, max_length=32, unique=True, validators=[inventory.validators.HostnameValueValidator()]),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 4 to 32 digits, letters and special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Device with this name already exists.'}, max_length=32, unique=True, validators=[inventory.validators.NameValueValidator()]),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 4 to 32 digits, letters and special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Group with this name already exists.'}, max_length=32, unique=True, validators=[inventory.validators.NameValueValidator()]),
        ),
    ]
