# Generated by Django 3.2.9 on 2022-01-18 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceinterface',
            name='descrip',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
