# Generated by Django 3.2.9 on 2022-01-14 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceinterface',
            options={'default_permissions': ['read', 'read_write'], 'permissions': []},
        ),
        migrations.AlterModelOptions(
            name='devicerawdata',
            options={'default_permissions': ['read', 'read_write'], 'permissions': []},
        ),
        migrations.AddField(
            model_name='device',
            name='device_interface',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.deviceinterface'),
        ),
        migrations.AddField(
            model_name='device',
            name='device_raw_data',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.devicerawdata'),
        ),
        migrations.AlterUniqueTogether(
            name='deviceinterface',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='devicerawdata',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='deviceinterface',
            name='device',
        ),
        migrations.RemoveField(
            model_name='devicerawdata',
            name='device',
        ),
    ]
