# Generated by Django 3.2.9 on 2021-12-20 22:08

from django.db import migrations, models
import inventory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.CharField(default='Device description.', error_messages={'invalid': 'Enter the correct description value. It must contain 8 to 16 digits, letters and special characters -, _, . or spaces.'}, max_length=256, validators=[inventory.validators.DescriptionValueValidator()], verbose_name='Device description'),
        ),
        migrations.AlterField(
            model_name='device',
            name='hostname',
            field=models.CharField(error_messages={'blank': 'IP / DNS name field is mandatory.', 'invalid': 'Enter a valid IP address or DNS resolvable hostname. It must contain 4 to 32 digits, letters and special characters -, _, . or spaces.', 'null': 'IP / DNS name field is mandatory.'}, max_length=32, unique=True, validators=[inventory.validators.HostnameValueValidator()], verbose_name='IP / DNS name'),
        ),
    ]
