# Generated by Django 3.2.9 on 2022-01-14 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20220114_1844'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deviceinterface',
            options={},
        ),
        migrations.AlterModelOptions(
            name='devicerawdata',
            options={},
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_interface',
        ),
        migrations.RemoveField(
            model_name='device',
            name='device_raw_data',
        ),
        migrations.AddField(
            model_name='deviceinterface',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.device'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='devicerawdata',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.device'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='deviceinterface',
            unique_together={('device', 'port')},
        ),
        migrations.AlterUniqueTogether(
            name='devicerawdata',
            unique_together={('device', 'command_name')},
        ),
    ]
