# Generated by Django 3.2.9 on 2022-01-18 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_deviceinterface_descrip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviceinterface',
            name='descrip',
        ),
    ]
