# Generated by Django 3.2.9 on 2022-01-14 17:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20220114_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='device_data',
        ),
        migrations.AddField(
            model_name='devicedata',
            name='device',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='inventory.device'),
            preserve_default=False,
        ),
    ]
