# Generated by Django 3.2.9 on 2021-12-21 11:25

from django.db import migrations, models
import django.db.models.deletion
import inventory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20211220_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(error_messages={'blank': 'Hostname field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 4 to 16 digits, letters and special characters -, _ or spaces.', 'null': 'Hostname field is mandatory.'}, max_length=16, unique=True, validators=[inventory.validators.NameValueValidator()], verbose_name='Device name'),
        ),
        migrations.AlterField(
            model_name='devicedata',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.device', unique=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 4 to 16 digits, letters and special characters -, _ or spaces.', 'null': 'Name field is mandatory.'}, max_length=16, unique=True, validators=[inventory.validators.NameValueValidator()], verbose_name='Group name'),
        ),
    ]
