# Generated by Django 3.2.9 on 2021-12-21 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_auto_20211221_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='credentials',
            field=models.ManyToManyField(blank=True, through='inventory.ColorCredentialRelation', to='inventory.Credential'),
        ),
        migrations.AlterField(
            model_name='color',
            name='devices',
            field=models.ManyToManyField(blank=True, through='inventory.ColorDeviceRelation', to='inventory.Device'),
        ),
        migrations.AlterField(
            model_name='color',
            name='groups',
            field=models.ManyToManyField(blank=True, through='inventory.ColorGroupRelation', to='inventory.Group'),
        ),
    ]
