# Generated by Django 3.2.9 on 2021-12-21 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_auto_20211221_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedata',
            name='device',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='inventory.device'),
        ),
    ]
