# Generated by Django 3.2.9 on 2022-01-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'permissions': [],
                'abstract': False,
                'default_permissions': ('one', 'two'),
            },
        ),
    ]
