# Generated by Django 3.2.9 on 2021-12-23 13:12

import administration.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='default_connection_password',
            field=models.CharField(blank=True, default='password', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='settings',
            name='default_connection_username',
            field=models.CharField(default='admin', max_length=64),
        ),
        migrations.AlterField(
            model_name='access',
            name='name',
            field=models.CharField(error_messages={'blank': 'Name field is mandatory.', 'invalid': 'Enter the correct name value. It must contain 4 to 32 digits, letters and special characters -, _ or spaces.', 'null': 'Name field is mandatory.', 'unique': 'Access with this name already exists.'}, max_length=32, unique=True, validators=[administration.validators.NameValueValidator()]),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='email',
            field=models.EmailField(blank=True, error_messages={'blank': 'E-mail field is mandatory.', 'invalid': 'Enter the correct e-mail value.', 'null': 'E-mail field is mandatory.', 'unique': 'Administrator with this e-mail already exists.'}, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='password',
            field=models.CharField(error_messages={'blank': 'Password field is mandatory.', 'invalid': 'Enter the correct password value. It requires at least one lowercase letter, one uppercase letter, one digit and one special character (@$!%*?&), minimum 8 characters.', 'null': 'Password field is mandatory.'}, max_length=128, validators=[administration.validators.PasswordValueValidator()]),
        ),
        migrations.AlterField(
            model_name='administrator',
            name='username',
            field=models.CharField(error_messages={'blank': 'Username field is mandatory.', 'invalid': 'Enter the correct username value. It must contain 4 to 32 digits, letters and spaces.', 'null': 'Username field is mandatory.', 'unique': 'Administrator with this username already exists.'}, max_length=32, unique=True, validators=[administration.validators.UsernameValueValidator()]),
        ),
    ]
