# Generated by Django 3.2.9 on 2021-12-23 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_auto_20211223_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='default_connection_password',
            field=models.CharField(default='password', max_length=64),
        ),
    ]
