# Generated by Django 3.2.9 on 2022-01-08 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administration', '0002_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
